version: '3.9'
services:
  web:
    build: .
    command: > 
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate && 
             python src/manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./src:/src
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:14
    volumes:
      - pgdata:/var/lib/postgresql/data/
    env_file:
      - ./.env
  redis:
    image: redis:6.2.6
  celery:
    restart: always
    build:
      context: .
    command: celery -A app worker -l info
    volumes:
      - ./src:/src
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
      - web
volumes:
  pgdata: