# Generated by Django 3.2.8 on 2021-11-06 07:52

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211105_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=300),
        ),
    ]
