# Generated by Django 3.2.8 on 2021-11-06 09:16

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_page_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=300),
        ),
        migrations.AlterField(
            model_name='wander',
            name='caption',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=255),
        ),
    ]
