# Generated by Django 4.0.1 on 2022-03-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20211109_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
